Correct input file in use: systemic/systemic_azimuts0_elevations90_point_src_dist1.1_point_src_az0_resolution_along_los0.1_RS_min_altitude0_RS_max_altitude1_wavelength391.4_emission_altitude90_max_angle_discretization1
Has_sky_emission: False
AzDistToLonLat 0.0 1.1 0.0 0.0001726573536336525 0.0 1.1
Has_ground_emission: True
lagorge 0.10361906322688955 0.7891042478910105
ALT MAP BOUNDS 5.037613394081269 6.836256605918731 44.31302139408126 46.111664605918726
0.01569612305760477
ALT MAP BOUNDS 5.036200993144891 6.8348442049823515 44.309575523615855 46.10821873545331
ALT MAP BOUNDS 5.036200993144891 6.8348442049823515 44.309575523615855 46.10821873545331
Initialization DONE
*******************************************************************************************************************************
STARTING calculation for obs:
Observation at point (5.936935, 45.212343), azimuth 0.0, elevation 90.0. Observed point at altitude 90.0, position (5.936935000000001, 45.212343000000004)
9 bins to compute
  0%|          | 0/9 [00:00<?, ?it/s]/home/bossel/These/Analysis/src/rayleigh/world.py:304: RuntimeWarning: divide by zero encountered in double_scalars
  I0 *= self.ground_map.GetArea(ilat) / RE ** 2
100%|██████████| 9/9 [00:00<00:00, 566.12it/s]
Computing DONE
3.94369672836391e-07 3.90654658372693e-07
Making and NOT saving plots...
ALL TIME SINCE START: 0.6592886447906494
